const pg = require('pg');
const { Pool } = pg;

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

//https://node-postgres.com/features/transactions
async function execWithClient(cb) {
  const client = await pool.connect();
  try {
    return await cb(client);
  } finally {
    client.release()
  }
}

async function close() {
  await pool.end();
}


async function init() {

  await pool.query(`
    CREATE TABLE IF NOT EXISTS "session" (
      "sid" varchar NOT NULL COLLATE "default",
      "sess" json NOT NULL,
      "expire" timestamp(6) NOT NULL
    )
    WITH (OIDS=FALSE);
  `, []);


  await pool.query(`
    CREATE TABLE IF NOT EXISTS auth_user (
      id UUID PRIMARY KEY,
      email varchar(80) UNIQUE
    );
  `, []);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS transaction_audit (
      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      url VARCHAR(2048), --max length of an url
      creation timestamp,
      user_id UUID --references auth_user(id)
    );
  `, []);

}

// init();

const query = (text, params) => pool.query(text, params);

module.exports = {
  pool,
  query,
  close,
  execWithClient
};
