CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);

ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX "IDX_session_expire" ON "session" ("expire");

-----------------------
CREATE TABLE auth_user (
  id UUID PRIMARY KEY,
  email varchar(80) UNIQUE
);

CREATE TABLE transaction_audit (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(20)
);

